import React from 'react'

// ─── Color Tokens ─────────────────────────────────────────────────
const INDIGO = '#4f46e5'

// ─── Login Page Styles ────────────────────────────────────────────
export const loginStyles: Record<string, React.CSSProperties> = {
  page: {
    minHeight: '100vh',
    background: 'linear-gradient(135deg, #f8fafc 0%, #f1f5f9 50%, #e0e7ff 100%)',
    display: 'flex',
    flexDirection: 'column',
    position: 'relative',
    overflow: 'hidden',
    fontFamily: "'Prompt', sans-serif",
  },
  bgCircle1: {
    position: 'absolute',
    top: '-200px',
    right: '-150px',
    width: '600px',
    height: '600px',
    borderRadius: '50%',
    background: 'radial-gradient(circle, rgba(99,102,241,0.08) 0%, transparent 70%)',
    pointerEvents: 'none',
  },
  bgCircle2: {
    position: 'absolute',
    bottom: '-100px',
    left: '-200px',
    width: '500px',
    height: '500px',
    borderRadius: '50%',
    background: 'radial-gradient(circle, rgba(124,58,237,0.06) 0%, transparent 70%)',
    pointerEvents: 'none',
  },

  // ─── Layout ───────────────────────────────────────────────────
  container: {
    flex: 1,
    display: 'flex',
    position: 'relative',
    zIndex: 5,
    maxWidth: '1200px',
    width: '100%',
    margin: '40px auto',
    padding: '0 24px',
    gap: '40px',
    alignItems: 'center',
  },

  // ─── Hero (Left) ──────────────────────────────────────────────
  heroPanel: {
    width: '45%',
    height: '640px',
    position: 'relative',
    borderRadius: '24px',
    overflow: 'hidden',
    flexShrink: 0,
    boxShadow: '0 20px 40px rgba(0, 0, 0, 0.06)',
  },
  heroImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    display: 'block',
  },
  heroOverlay: {
    position: 'absolute',
    inset: 0,
    background:
      'linear-gradient(160deg, rgba(15,23,42,0.1) 0%, rgba(79,70,229,0.3) 50%, rgba(79,70,229,0.7) 100%)',
    zIndex: 1,
  },
  heroContent: {
    position: 'absolute',
    inset: 0,
    zIndex: 2,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-end',
    padding: '40px 32px',
  },
  heroBadge: {
    display: 'inline-block',
    backgroundColor: 'rgba(255,255,255,0.25)',
    backdropFilter: 'blur(12px)',
    border: '1px solid rgba(255,255,255,0.4)',
    color: '#1e1b4b',
    fontSize: 12,
    fontWeight: 600,
    padding: '6px 14px',
    borderRadius: 20,
    marginBottom: 16,
    width: 'fit-content',
  },
  heroTitle: {
    color: '#fff',
    fontSize: 30,
    fontWeight: 700,
    lineHeight: 1.3,
    margin: '0 0 12px',
    textShadow: '0 2px 10px rgba(0,0,0,0.25)',
  },
  heroDesc: {
    color: 'rgba(255,255,255,0.95)',
    fontSize: 14,
    lineHeight: 1.7,
    margin: '0 0 28px',
    textShadow: '0 1px 4px rgba(0,0,0,0.15)',
  },
  heroStats: {
    display: 'flex',
    alignItems: 'center',
    gap: 0,
    backgroundColor: 'rgba(255,255,255,0.2)',
    backdropFilter: 'blur(16px)',
    border: '1px solid rgba(255,255,255,0.3)',
    borderRadius: 18,
    padding: '16px 0',
    boxShadow: '0 8px 32px rgba(0,0,0,0.05)',
  },
  statItem: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 2,
  },
  statNum: { color: '#1e1b4b', fontSize: 20, fontWeight: 700 },
  statLabel: { color: 'rgba(30,27,75,0.8)', fontSize: 12, fontWeight: 500 },
  statDivider: { width: '1px', height: 32, backgroundColor: 'rgba(30,27,75,0.15)' },

  // ─── Form (Right) ─────────────────────────────────────────────
  formPanel: {
    flex: 1,
    backgroundColor: '#ffffff',
    borderRadius: '24px',
    border: '1px solid #e2e8f0',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 20px 40px rgba(0, 0, 0, 0.03)',
    height: '640px',
  },
  formInner: {
    width: '100%',
    maxWidth: 420,
    padding: '32px 40px',
  },
  formHeader: { textAlign: 'center', marginBottom: 24 },
  formIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 16,
    background: 'rgba(99,102,241,0.1)',
    border: '1px solid rgba(99,102,241,0.2)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    margin: '0 auto 14px',
  },
  formTitle: { fontSize: 28, fontWeight: 700, color: '#0f172a', margin: '0 0 6px' },
  formSubtitle: { fontSize: 13, color: '#64748b', margin: 0, fontWeight: 400 },

  // ─── Fields ───────────────────────────────────────────────────
  fieldGroup: { marginBottom: 16 },
  label: {
    display: 'block',
    fontSize: 13,
    fontWeight: 600,
    color: '#334155',
    marginBottom: 6,
  },
  inputWrapper: { position: 'relative', display: 'flex', alignItems: 'center' },
  inputIcon: { position: 'absolute', left: 14, fontSize: 16, zIndex: 1, userSelect: 'none' },
  input: {
    width: '100%',
    padding: '12px 14px 12px 42px',
    borderRadius: 10,
    border: '1.5px solid #cbd5e1',
    fontSize: 14,
    color: '#0f172a',
    backgroundColor: '#ffffff',
    outline: 'none',
    boxSizing: 'border-box',
    fontFamily: "'Prompt', sans-serif",
    transition: 'border-color 0.2s, box-shadow 0.2s',
  },
  eyeBtn: {
    position: 'absolute',
    right: 12,
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontSize: 16,
    padding: 4,
    color: '#64748b',
  },

  // ─── Feedback ─────────────────────────────────────────────────
  errorBox: {
    backgroundColor: '#fef2f2',
    border: '1px solid #fecaca',
    borderRadius: 10,
    color: '#dc2626',
    fontSize: 13,
    padding: '10px 14px',
    marginBottom: 14,
    display: 'flex',
    alignItems: 'center',
    gap: 6,
  },

  // ─── Submit ───────────────────────────────────────────────────
  submitBtn: {
    width: '100%',
    background: 'linear-gradient(135deg, #4f46e5 0%, #7c3aed 100%)',
    border: 'none',
    color: '#fff',
    padding: '13px',
    borderRadius: 12,
    fontSize: 15,
    fontWeight: 600,
    fontFamily: "'Prompt', sans-serif",
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    boxShadow: '0 4px 16px rgba(79,70,229,0.2)',
    transition: 'opacity 0.2s, transform 0.1s',
    marginBottom: 16,
  },
  spinner: {
    width: 16,
    height: 16,
    border: '2px solid rgba(255,255,255,0.3)',
    borderTopColor: '#fff',
    borderRadius: '50%',
    display: 'inline-block',
    animation: 'spin 0.7s linear infinite',
  },

  // ─── Divider ──────────────────────────────────────────────────
  divider: { display: 'flex', alignItems: 'center', gap: 10, marginBottom: 12 },
  dividerLine: { flex: 1, height: '1px', backgroundColor: '#e2e8f0' },
  dividerText: { fontSize: 12, color: '#94a3b8' },

  // ─── Register Link ────────────────────────────────────────────
  registerText: { textAlign: 'center', fontSize: 13, color: '#475569', margin: '0 0 14px' },
  registerLink: {
    color: '#4f46e5',
    cursor: 'pointer',
    fontWeight: 600,
    textDecoration: 'underline',
    textDecorationColor: 'rgba(79,70,229,0.3)',
  },

  // ─── Trust Badge ──────────────────────────────────────────────
  trustBadge: {
    textAlign: 'center',
    fontSize: 12,
    color: '#475569',
    backgroundColor: 'rgba(79,70,229,0.05)',
    border: '1px solid rgba(79,70,229,0.12)',
    borderRadius: 8,
    padding: '8px 12px',
  },
}
