import React from 'react'

// ─── Login Page Styles — Royal Purple-Blue Edition ──────────────────────
// Design: Two-column layout — high-impact imagery left, clean form right
// Colors: Deep Space (#050714), Royal Violet (#7C3AED), Royal Blue (#1D4ED8)
// ──────────────────────────────────────────────────────────────────────────

export const loginStyles: Record<string, React.CSSProperties> = {
  page: {
    minHeight: '100vh',
    backgroundColor: 'var(--color-bg)',
    color: 'var(--color-text)',
    fontFamily: "'Inter', 'Kanit', sans-serif",
    display: 'flex',
    flexDirection: 'column',
    position: 'relative',
    overflow: 'hidden',
  },

  container: {
    flex: 1,
    display: 'flex',
    position: 'relative',
    zIndex: 5,
    maxWidth: '1240px',
    width: '100%',
    margin: '130px auto 40px',
    padding: '0 24px',
    gap: '36px',
    alignItems: 'stretch',
  },

  // ── Hero (Left) ──
  heroPanel: {
    width: '45%',
    minHeight: '640px',
    position: 'relative',
    borderRadius: '24px',
    overflow: 'hidden',
    flexShrink: 0,
    border: '1px solid var(--color-border)',
    backgroundColor: 'var(--color-card)',
  },
  heroImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    display: 'block',
    opacity: 0.75,
  },
  heroOverlay: {
    position: 'absolute',
    inset: 0,
    background: 'linear-gradient(to top, rgba(5,7,20,0.95) 0%, rgba(5,7,20,0.40) 60%, transparent 100%)',
    zIndex: 1,
  },
  heroContent: {
    position: 'absolute',
    inset: 0,
    zIndex: 2,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-end',
    padding: '40px 36px',
  },
  heroBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    backgroundColor: 'rgba(124, 58, 237, 0.2)',
    backdropFilter: 'blur(8px)',
    border: '1px solid rgba(124, 58, 237, 0.4)',
    color: '#ffffff',
    fontSize: '11px',
    fontWeight: 700,
    padding: '6px 14px',
    borderRadius: '9999px',
    marginBottom: '16px',
    width: 'fit-content',
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    fontFamily: "'Manrope', 'Kanit', sans-serif",
  },
  heroTitle: {
    color: '#ffffff',
    fontSize: '32px',
    fontWeight: 700,
    lineHeight: 1.2,
    margin: '0 0 10px',
    fontFamily: "'Manrope', 'Kanit', sans-serif",
    letterSpacing: '-0.03em',
  },
  heroDesc: {
    color: 'rgba(255,255,255,0.75)',
    fontSize: '14px',
    lineHeight: 1.65,
    margin: '0 0 24px',
    fontWeight: 400,
    fontFamily: "'Inter', 'Kanit', sans-serif",
  },
  heroStats: {
    display: 'flex',
    alignItems: 'center',
    backgroundColor: 'rgba(124, 58, 237, 0.12)',
    backdropFilter: 'blur(12px)',
    border: '1px solid rgba(124, 58, 237, 0.25)',
    borderRadius: '16px',
    padding: '14px 0',
  },
  statItem: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '2px',
  },
  statNum: {
    color: '#ffffff',
    fontSize: '18px',
    fontWeight: 700,
    lineHeight: 1.2,
    fontFamily: "'Manrope', 'Kanit', sans-serif",
  },
  statLabel: {
    color: 'rgba(255,255,255,0.60)',
    fontSize: '11px',
    fontWeight: 500,
    fontFamily: "'Inter', 'Kanit', sans-serif",
  },
  statDivider: {
    width: '1px',
    height: '28px',
    backgroundColor: 'rgba(124, 58, 237, 0.25)',
  },

  // ── Form (Right) ──
  formPanel: {
    flex: 1,
    backgroundColor: 'var(--color-card)',
    borderRadius: '24px',
    border: '1px solid var(--color-border)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 12px 36px rgba(124, 58, 237, 0.1)',
    minHeight: '640px',
    position: 'relative',
  },
  formInner: {
    width: '100%',
    maxWidth: '440px',
    padding: '40px',
    position: 'relative',
    zIndex: 1,
  },
  formHeader: {
    marginBottom: '24px',
  },
  formIconWrap: {
    width: '48px',
    height: '48px',
    borderRadius: '14px',
    backgroundColor: 'rgba(124, 58, 237, 0.15)',
    border: '1px solid rgba(124, 58, 237, 0.3)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: '16px',
    fontSize: '22px',
    color: '#7C3AED',
  },
  formTitle: {
    fontSize: '28px',
    fontWeight: 700,
    color: 'var(--color-text)',
    margin: '0 0 4px',
    fontFamily: "'Manrope', 'Kanit', sans-serif",
    letterSpacing: '-0.03em',
  },
  formSubtitle: {
    fontSize: '13.5px',
    color: 'var(--color-text-muted)',
    margin: 0,
    fontWeight: 500,
    fontFamily: "'Inter', 'Kanit', sans-serif",
  },

  // ── Role Toggle ──
  roleToggleContainer: {
    display: 'flex',
    backgroundColor: 'var(--color-surface)',
    padding: '4px',
    borderRadius: '9999px',
    marginBottom: '22px',
    gap: '4px',
    border: '1px solid var(--color-border)',
  },
  roleBtn: {
    flex: 1,
    padding: '10px 8px',
    border: 'none',
    borderRadius: '9999px',
    backgroundColor: 'transparent',
    color: 'var(--color-text-muted)',
    fontWeight: 700,
    fontSize: '12px',
    letterSpacing: '0.04em',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '5px',
    whiteSpace: 'nowrap',
    fontFamily: "'Inter', 'Kanit', sans-serif",
  },
  roleBtnActive: {
    backgroundImage: 'linear-gradient(135deg, #7C3AED 0%, #1D4ED8 100%)',
    backgroundColor: 'transparent',
    color: '#ffffff',
    boxShadow: '0 4px 14px rgba(124, 58, 237, 0.4)',
  },

  // ── Fields ──
  fieldGroup: {
    marginBottom: '16px',
  },
  label: {
    display: 'block',
    fontSize: '12px',
    fontWeight: 700,
    color: 'var(--color-text)',
    marginBottom: '6px',
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    fontFamily: "'Inter', 'Kanit', sans-serif",
  },
  inputWrapper: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
  },
  inputIcon: {
    position: 'absolute',
    left: '14px',
    fontSize: '15px',
    zIndex: 1,
    userSelect: 'none',
    color: 'var(--color-text-muted)',
  },
  input: {
    width: '100%',
    padding: '12px 14px 12px 42px',
    borderRadius: '12px',
    border: '1px solid var(--color-border)',
    fontSize: '14px',
    color: 'var(--color-text)',
    backgroundColor: 'var(--color-surface)',
    outline: 'none',
    boxSizing: 'border-box',
    transition: 'border-color 0.18s',
    lineHeight: 1.5,
    fontFamily: "'Inter', 'Kanit', sans-serif",
  },
  eyeBtn: {
    position: 'absolute',
    right: '12px',
    background: 'none',
    backgroundColor: 'transparent',
    border: 'none',
    cursor: 'pointer',
    fontSize: '15px',
    padding: '4px',
    color: 'var(--color-text-muted)',
    lineHeight: 1,
  },

  // ── Feedback ──
  errorBox: {
    backgroundColor: 'rgba(239, 68, 68, 0.12)',
    border: '1px solid #ef4444',
    borderRadius: '12px',
    color: '#f87171',
    fontSize: '13px',
    padding: '10px 14px',
    marginBottom: '14px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    lineHeight: 1.5,
    fontWeight: 500,
    fontFamily: "'Inter', 'Kanit', sans-serif",
  },

  // ── Submit ──
  submitBtn: {
    width: '100%',
    backgroundImage: 'linear-gradient(135deg, #7C3AED 0%, #1D4ED8 100%)',
    backgroundColor: 'transparent',
    border: 'none',
    color: '#ffffff',
    padding: '13px',
    borderRadius: '9999px',
    fontSize: '13.5px',
    fontWeight: 700,
    letterSpacing: '0.06em',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    transition: 'all 0.2s ease',
    marginBottom: '18px',
    fontFamily: "'Inter', 'Kanit', sans-serif",
    boxShadow: '0 4px 15px rgba(124, 58, 237, 0.4)',
  },
  spinner: {
    width: '14px',
    height: '14px',
    border: '2px solid rgba(255,255,255,0.3)',
    borderTopColor: '#ffffff',
    borderRadius: '50%',
    display: 'inline-block',
    animation: 'clay-spin 0.7s linear infinite',
  },

  // ── Divider ──
  divider: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    marginBottom: '16px',
  },
  dividerLine: {
    flex: 1,
    height: '1px',
    backgroundColor: 'var(--color-border)',
  },
  dividerText: {
    fontSize: '11px',
    color: 'var(--color-text-muted)',
    fontWeight: 700,
    letterSpacing: '0.08em',
    fontFamily: "'Inter', 'Kanit', sans-serif",
  },

  // ── Register Link ──
  registerText: {
    textAlign: 'center',
    fontSize: '13.5px',
    color: 'var(--color-text-muted)',
    margin: '0 0 16px',
    fontFamily: "'Inter', 'Kanit', sans-serif",
  },
  registerLink: {
    color: '#7C3AED',
    cursor: 'pointer',
    fontWeight: 700,
    textDecoration: 'underline',
    fontFamily: "'Inter', 'Kanit', sans-serif",
  },

  // ── Trust Badge ──
  trustBadge: {
    textAlign: 'center',
    fontSize: '11.5px',
    color: 'var(--color-text-muted)',
    backgroundColor: 'var(--color-surface)',
    border: '1px solid var(--color-border)',
    borderRadius: '10px',
    padding: '8px 12px',
    fontWeight: 500,
    fontFamily: "'Inter', 'Kanit', sans-serif",
  },
}
