import React from 'react'

// ─── Register Page Styles ──────────────────────────────────────────────────
// Design: Two-column layout — branding/steps panel left, form right
// Matches login design tokens for visual consistency
// ──────────────────────────────────────────────────────────────────────────

export const registerStyles: Record<string, React.CSSProperties> = {

  // ── Page wrapper ──────────────────────────────────────────────
  page: {
    minHeight: '100vh',
    background: '#f9fafb',
    display: 'flex',
    flexDirection: 'column',
    position: 'relative',
  },
  bgCircle1: {
    position: 'absolute',
    top: '-100px',
    right: '-80px',
    width: '360px',
    height: '360px',
    borderRadius: '50%',
    background: 'radial-gradient(circle, rgba(29,78,216,0.05) 0%, transparent 70%)',
    pointerEvents: 'none',
  },
  bgCircle2: {
    position: 'absolute',
    bottom: '-60px',
    left: '-100px',
    width: '300px',
    height: '300px',
    borderRadius: '50%',
    background: 'radial-gradient(circle, rgba(29,78,216,0.04) 0%, transparent 70%)',
    pointerEvents: 'none',
  },
  bgCircle3: { display: 'none' },

  // ── Layout ───────────────────────────────────────────────────
  main: {
    flex: 1,
    display: 'flex',
    position: 'relative',
    zIndex: 5,
    maxWidth: '1160px',
    margin: '40px auto',
    width: 'calc(100% - 48px)',
    background: '#ffffff',
    borderRadius: '16px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.06), 0 4px 6px rgba(0,0,0,0.04)',
    border: '1px solid #e5e7eb',
    overflow: 'hidden',
    minHeight: '640px',
  },

  // ── Hero Panel (Left) ─────────────────────────────────────────
  heroPanel: {
    width: '38%',
    position: 'relative',
    overflow: 'hidden',
    flexShrink: 0,
    background: '#0f172a',
  },
  heroImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    display: 'block',
    opacity: 0.25,
  },
  heroOverlay: {
    position: 'absolute',
    inset: 0,
    background: 'linear-gradient(160deg, #1e3a8a 0%, #1d4ed8 60%, #1e40af 100%)',
    opacity: 0.9,
  },
  heroContent: {
    position: 'absolute',
    inset: 0,
    zIndex: 2,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-end',
    padding: '36px 32px',
  },
  heroBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    background: 'rgba(255,255,255,0.15)',
    backdropFilter: 'blur(8px)',
    border: '1px solid rgba(255,255,255,0.2)',
    color: '#ffffff',
    fontSize: '11.5px',
    fontWeight: 600,
    padding: '5px 12px',
    borderRadius: '20px',
    marginBottom: '14px',
    width: 'fit-content',
    letterSpacing: '0.02em',
  },
  heroTitle: {
    color: '#fff',
    fontSize: '22px',
    fontWeight: 700,
    lineHeight: 1.35,
    margin: '0 0 10px',
  },
  heroDesc: {
    color: 'rgba(255,255,255,0.75)',
    fontSize: '13px',
    lineHeight: 1.7,
    margin: '0 0 24px',
  },
  heroSteps: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0px',
    background: 'rgba(255,255,255,0.1)',
    border: '1px solid rgba(255,255,255,0.15)',
    borderRadius: '12px',
    padding: '16px 18px',
    backdropFilter: 'blur(10px)',
  },
  heroStep: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    position: 'relative',
    paddingBottom: '4px',
  },
  heroStepDot: {
    width: '34px',
    height: '34px',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    transition: 'all 0.2s',
  },
  heroStepLabel: {
    fontSize: '13px',
    lineHeight: 1.3,
    color: 'rgba(255,255,255,0.9)',
    fontWeight: 500,
  },
  heroStepNum: {
    fontSize: '10.5px',
    color: 'rgba(255,255,255,0.5)',
    marginTop: '1px',
  },
  heroStepLine: {
    position: 'absolute',
    left: '16px',
    top: '38px',
    width: '2px',
    height: '22px',
    borderRadius: '2px',
    transition: 'background-color 0.2s',
  },

  // ── Form Panel (Right) ────────────────────────────────────────
  formPanel: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '32px 0',
    backgroundColor: '#ffffff',
  },
  formInner: {
    width: '100%',
    maxWidth: '640px',
    padding: '0 40px',
    animation: 'fadeUp 0.3s ease both',
  },
  formHeader: {
    textAlign: 'center',
    marginBottom: '20px',
  },
  formIconWrap: {
    width: '48px',
    height: '48px',
    borderRadius: '12px',
    background: '#eff6ff',
    border: '1px solid #bfdbfe',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    margin: '0 auto 12px',
  },
  formTitle: {
    fontSize: '20px',
    fontWeight: 700,
    color: '#111827',
    margin: '0 0 4px',
  },
  formSubtitle: {
    fontSize: '13px',
    color: '#6b7280',
    margin: 0,
  },

  // ── Progress Bar ──────────────────────────────────────────────
  progressTrack: {
    height: '3px',
    borderRadius: '3px',
    backgroundColor: '#e5e7eb',
    marginBottom: '24px',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: '3px',
    background: 'linear-gradient(90deg, #1d4ed8, #3b82f6)',
    transition: 'width 0.35s ease',
  },

  // ── Input ─────────────────────────────────────────────────────
  input: {
    width: '100%',
    padding: '10px 12px',
    borderRadius: '8px',
    border: '1.5px solid #e5e7eb',
    fontSize: '13.5px',
    color: '#111827',
    backgroundColor: '#ffffff',
    outline: 'none',
    boxSizing: 'border-box',
    marginBottom: 0,
    transition: 'border-color 0.15s, box-shadow 0.15s',
    lineHeight: 1.5,
  },

  // ── Feedback ─────────────────────────────────────────────────
  errorBox: {
    background: '#fef2f2',
    border: '1px solid #fecaca',
    borderRadius: '8px',
    color: '#dc2626',
    fontSize: '13px',
    padding: '9px 12px',
    marginBottom: '12px',
    lineHeight: 1.5,
  },

  // ── Navigation Buttons ────────────────────────────────────────
  btnRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: '16px',
    gap: '12px',
  },
  backBtn: {
    background: '#ffffff',
    border: '1.5px solid #e5e7eb',
    color: '#6b7280',
    padding: '10px 20px',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '13.5px',
    fontWeight: 500,
    transition: 'all 0.15s',
  },
  nextBtn: {
    flex: 1,
    background: '#1d4ed8',
    border: 'none',
    color: '#fff',
    padding: '11px 24px',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '13.5px',
    fontWeight: 600,
    transition: 'background-color 0.15s, transform 0.1s',
    letterSpacing: '0.01em',
  },
}
