import React from 'react'

export const registerStyles: Record<string, React.CSSProperties> = {

  page: {
    minHeight: '100vh',
    backgroundColor: 'var(--color-bg)',
    color: 'var(--color-text)',
    fontFamily: "'Inter', 'Kanit', sans-serif",
    display: 'flex',
    flexDirection: 'column',
    position: 'relative',
  },
  bgCircle1: { display: 'none' },
  bgCircle2: { display: 'none' },
  bgCircle3: { display: 'none' },

  main: {
    flex: 1,
    display: 'flex',
    position: 'relative',
    zIndex: 5,
    maxWidth: '1240px',
    margin: '130px auto 80px',
    width: 'calc(100% - 48px)',
    backgroundColor: 'var(--color-card)',
    borderRadius: '24px',
    boxShadow: '0 12px 36px rgba(35, 64, 167, 0.12)',
    border: '1px solid var(--color-border)',
    overflow: 'hidden',
    minHeight: '640px',
  },

  heroPanel: {
    width: '40%',
    position: 'relative',
    overflow: 'hidden',
    flexShrink: 0,
    backgroundColor: 'var(--color-card)',
    borderRight: '1px solid var(--color-border)',
  },
  heroImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    display: 'block',
    opacity: 0.35,
  },
  heroOverlay: {
    position: 'absolute',
    inset: 0,
    background: 'linear-gradient(160deg, rgba(5,7,20,0.95) 0%, rgba(5,7,20,0.85) 100%)',
  },
  heroContent: {
    position: 'absolute',
    inset: 0,
    zIndex: 2,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-end',
    padding: '40px 36px',
  },
  heroBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    backgroundColor: 'rgba(35, 64, 167, 0.2)',
    backdropFilter: 'blur(8px)',
    border: '1px solid rgba(35, 64, 167, 0.4)',
    color: '#ffffff',
    fontSize: '11px',
    fontWeight: 700,
    padding: '6px 14px',
    borderRadius: '9999px',
    marginBottom: '16px',
    width: 'fit-content',
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    fontFamily: "'Manrope', 'Kanit', sans-serif",
  },
  heroTitle: {
    color: '#ffffff',
    fontSize: '26px',
    fontWeight: 700,
    lineHeight: 1.25,
    margin: '0 0 10px',
    fontFamily: "'Manrope', 'Kanit', sans-serif",
    letterSpacing: '-0.03em',
  },
  heroDesc: {
    color: 'rgba(255,255,255,0.70)',
    fontSize: '13.5px',
    lineHeight: 1.65,
    margin: '0 0 24px',
    fontFamily: "'Inter', 'Kanit', sans-serif",
  },
  heroSteps: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0px',
    backgroundColor: 'rgba(35, 64, 167, 0.1)',
    border: '1px solid rgba(35, 64, 167, 0.25)',
    borderRadius: '16px',
    padding: '16px 18px',
  },
  heroStep: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    position: 'relative',
    paddingBottom: '4px',
  },
  heroStepDot: {
    width: '34px',
    height: '34px',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    transition: 'all 0.2s',
  },
  heroStepLabel: {
    fontSize: '13px',
    lineHeight: 1.3,
    color: '#ffffff',
    fontWeight: 700,
    fontFamily: "'Inter', 'Kanit', sans-serif",
  },
  heroStepNum: {
    fontSize: '10.5px',
    color: 'rgba(255,255,255,0.5)',
    marginTop: '1px',
  },
  heroStepLine: {
    position: 'absolute',
    left: '16px',
    top: '38px',
    width: '2px',
    height: '22px',
    borderRadius: '2px',
    transition: 'background-color 0.2s',
  },

  formPanel: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '36px 0',
    backgroundColor: 'var(--color-card)',
  },
  formInner: {
    width: '100%',
    maxWidth: '640px',
    padding: '0 40px',
  },
  formHeader: {
    textAlign: 'center',
    marginBottom: '24px',
  },
  formIconWrap: {
    width: '48px',
    height: '48px',
    borderRadius: '14px',
    backgroundColor: 'rgba(35, 64, 167, 0.15)',
    border: '1px solid rgba(35, 64, 167, 0.3)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    margin: '0 auto 14px',
    fontSize: '22px',
    color: '#2340A7',
  },
  formTitle: {
    fontFamily: "'Manrope', 'Kanit', sans-serif",
    fontSize: '26px',
    fontWeight: 700,
    color: 'var(--color-text)',
    margin: '0 0 6px',
    letterSpacing: '-0.02em',
  },
  formSubtitle: {
    fontSize: '15px',
    color: 'var(--color-text-muted)',
    margin: 0,
    fontWeight: 500,
    fontFamily: "'Inter', 'Kanit', sans-serif",
  },

  progressTrack: {
    height: '6px',
    borderRadius: '6px',
    backgroundColor: 'var(--color-surface)',
    marginBottom: '24px',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: '6px',
    backgroundImage: 'linear-gradient(135deg, #2340A7 0%, #2563EB 100%)',
    backgroundColor: 'transparent',
    transition: 'width 0.35s ease',
  },

  input: {
    width: '100%',
    padding: '13px 16px',
    borderRadius: '12px',
    border: '1px solid var(--color-border)',
    fontSize: '16px',
    color: 'var(--color-text)',
    backgroundColor: 'var(--color-surface)',
    outline: 'none',
    boxSizing: 'border-box',
    marginBottom: 0,
    transition: 'border-color 0.15s',
    lineHeight: 1.5,
    fontFamily: "'Inter', 'Kanit', sans-serif",
  },

  errorBox: {
    backgroundColor: 'rgba(239, 68, 68, 0.12)',
    border: '1px solid #ef4444',
    borderRadius: '12px',
    color: '#f87171',
    fontSize: '14.5px',
    padding: '12px 16px',
    marginBottom: '16px',
    lineHeight: 1.5,
    fontWeight: 600,
    fontFamily: "'Inter', 'Kanit', sans-serif",
  },

  btnRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: '24px',
    gap: '12px',
  },
  backBtn: {
    backgroundColor: 'transparent',
    border: '1px solid var(--color-border)',
    color: 'var(--color-text-muted)',
    padding: '13px 26px',
    borderRadius: '9999px',
    cursor: 'pointer',
    fontSize: '15.5px',
    fontWeight: 700,
    fontFamily: "'Inter', 'Kanit', sans-serif",
    transition: 'all 0.15s',
  },
  nextBtn: {
    flex: 1,
    backgroundImage: 'linear-gradient(135deg, #2340A7 0%, #2563EB 100%)',
    backgroundColor: 'transparent',
    border: 'none',
    color: '#ffffff',
    padding: '14px 28px',
    borderRadius: '9999px',
    cursor: 'pointer',
    fontSize: '15.5px',
    fontWeight: 700,
    letterSpacing: '0.04em',
    fontFamily: "'Inter', 'Kanit', sans-serif",
    transition: 'all 0.2s ease',
    boxShadow: '0 4px 15px rgba(35, 64, 167, 0.4)',
  },
}
