import React from 'react'

export const statusStyles: Record<string, React.CSSProperties> = {
  page: {
    minHeight: '100vh',
    backgroundColor: 'var(--color-bg)',
    color: 'var(--color-text)',
    fontFamily: "'Inter', 'Kanit', sans-serif",
    display: 'flex',
    flexDirection: 'column',
    position: 'relative',
  },

  bgCircle1: { display: 'none' },
  bgCircle2: { display: 'none' },
  bgCircle3: { display: 'none' },

  main: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: '130px 24px 80px',
    position: 'relative',
    zIndex: 1,
    maxWidth: '1240px',
    margin: '0 auto',
    width: '100%',
  },

  pageHeader: {
    textAlign: 'center',
    marginBottom: '36px',
  },
  pageBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    border: '1px solid rgba(124, 58, 237, 0.4)',
    backgroundColor: 'rgba(124, 58, 237, 0.15)',
    borderRadius: '9999px',
    padding: '6px 14px',
    fontSize: '11px',
    color: '#ffffff',
    fontWeight: 700,
    marginBottom: '16px',
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    fontFamily: "'Manrope', 'Kanit', sans-serif",
  },
  pageTitle: {
    fontFamily: "'Manrope', 'Kanit', sans-serif",
    fontSize: '32px',
    fontWeight: 700,
    color: 'var(--color-text)',
    margin: '0 0 8px',
    letterSpacing: '-0.03em',
  },
  pageSubtitle: {
    fontSize: '14.5px',
    color: 'var(--color-text-muted)',
    margin: 0,
    lineHeight: 1.6,
    fontFamily: "'Inter', 'Kanit', sans-serif",
  },

  card: {
    width: '100%',
    maxWidth: '680px',
    backgroundColor: 'var(--color-card)',
    border: '1px solid var(--color-border)',
    borderRadius: '24px',
    padding: '36px 40px',
    boxShadow: '0 12px 36px rgba(124, 58, 237, 0.1)',
    marginBottom: '20px',
  },

  greeting: {
    fontFamily: "'Manrope', 'Kanit', sans-serif",
    fontSize: '22px',
    fontWeight: 700,
    color: 'var(--color-text)',
    marginBottom: '4px',
  },
  greetingSub: {
    fontSize: '14px',
    color: '#cbd5e1',
    marginBottom: '28px',
    lineHeight: 1.6,
    fontFamily: "'Inter', 'Kanit', sans-serif",
  },

  stepper: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '36px',
    position: 'relative',
  },
  stepItem: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '8px',
    zIndex: 2,
    flex: 1,
  },
  stepCircle: {
    width: '40px',
    height: '40px',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 700,
    fontSize: '14px',
    transition: 'all 0.25s ease',
    border: '2px solid transparent',
    fontFamily: "'Manrope', 'Kanit', sans-serif",
  },
  stepLabel: {
    fontSize: '12px',
    fontWeight: 600,
    color: 'var(--color-text-muted)',
    textAlign: 'center',
    whiteSpace: 'nowrap',
    fontFamily: "'Inter', 'Kanit', sans-serif",
  },
  stepLine: {
    flex: 1,
    height: '2px',
    backgroundColor: 'var(--color-border)',
    margin: '0 -8px 24px',
    zIndex: 1,
    transition: 'background-color 0.25s ease',
  },

  infoGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '14px',
    marginBottom: '28px',
  },
  infoItem: {
    backgroundColor: 'var(--color-surface)',
    border: '1px solid var(--color-border)',
    borderRadius: '14px',
    padding: '14px 16px',
  },
  infoLabel: {
    fontSize: '11px',
    color: '#94a3b8',
    fontWeight: 600,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    marginBottom: '4px',
    display: 'block',
    fontFamily: "'Inter', 'Kanit', sans-serif",
  },
  infoValue: {
    fontSize: '14px',
    color: '#ffffff',
    fontWeight: 600,
    fontFamily: "'Inter', 'Kanit', sans-serif",
  },

  statusBox: {
    borderRadius: '16px',
    padding: '24px',
    marginBottom: '28px',
    display: 'flex',
    gap: '16px',
    alignItems: 'flex-start',
  },

  pendingBox: {
    backgroundColor: 'rgba(234, 179, 8, 0.1)',
    border: '1px solid rgba(234, 179, 8, 0.3)',
    color: '#eab308',
  },
  approvedBox: {
    backgroundColor: 'rgba(34, 197, 94, 0.1)',
    border: '1px solid rgba(34, 197, 94, 0.3)',
    color: '#22c55e',
  },
  rejectedBox: {
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    border: '1px solid rgba(239, 68, 68, 0.3)',
    color: '#ef4444',
  },

  statusBoxIcon: {
    fontSize: '28px',
    lineHeight: 1,
    flexShrink: 0,
    marginTop: '2px',
  },
  statusBoxTitle: {
    fontFamily: "'Manrope', 'Kanit', sans-serif",
    fontSize: '16px',
    fontWeight: 700,
    margin: '0 0 6px',
  },
  statusBoxDesc: {
    fontSize: '13.5px',
    lineHeight: 1.65,
    margin: 0,
    opacity: 0.9,
    fontFamily: "'Inter', 'Kanit', sans-serif",
  },

  actionArea: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  loginBtn: {
    width: '100%',
    backgroundImage: 'linear-gradient(135deg, #7C3AED 0%, #1D4ED8 100%)',
    backgroundColor: 'transparent',
    color: '#ffffff',
    border: 'none',
    borderRadius: '9999px',
    padding: '14px',
    fontSize: '14px',
    fontWeight: 700,
    letterSpacing: '0.04em',
    cursor: 'pointer',
    textAlign: 'center',
    boxShadow: '0 4px 16px rgba(124, 58, 237, 0.4)',
    fontFamily: "'Inter', 'Kanit', sans-serif",
  },
  reapplyBtn: {
    width: '100%',
    backgroundImage: 'linear-gradient(135deg, #7C3AED 0%, #1D4ED8 100%)',
    backgroundColor: 'transparent',
    color: '#ffffff',
    border: 'none',
    borderRadius: '9999px',
    padding: '14px',
    fontSize: '14px',
    fontWeight: 700,
    letterSpacing: '0.04em',
    cursor: 'pointer',
    textAlign: 'center',
    boxShadow: '0 4px 16px rgba(124, 58, 237, 0.4)',
    fontFamily: "'Inter', 'Kanit', sans-serif",
  },
  contactBtn: {
    width: '100%',
    backgroundColor: 'var(--color-surface)',
    border: '1px solid var(--color-border)',
    color: 'var(--color-text)',
    borderRadius: '9999px',
    padding: '13px',
    fontSize: '13.5px',
    fontWeight: 600,
    cursor: 'pointer',
    textAlign: 'center',
    fontFamily: "'Inter', 'Kanit', sans-serif",
  },
}
